---

- name: Install packages
  apt:
    name:
      - python3 
      - python3-dev 
      - python3-venv 
      - python3-pip 
      - git 
      - openjdk-11-jre-headless 
      - build-essential 

- name: Install python modules
  pip:
    name:
      - setuptools
      - wheel
      - Red-DiscordBot

- name: Create RedBot User
  user:
    name: redbot
    shell: /bin/bash

- name: Create data directory
  file: 
    path: "{{ data_path }}"
    state: directory
    mode: "0755"
    owner: redbot
    group: redbot
      
- name: Create instance configuration directory
  file:
    path: /home/redbot/.config/Red-DiscordBot
    state: directory
    mode: 0755
    owner: redbot
    group: redbot

- name: Create instance configuration
  template:
    src: config.json.j2
    dest: /home/redbot/.config/Red-DiscordBot/config.json
    owner: redbot
    group: redbot

- name: Create instance directory
  file:
    path: '{{ data_path + "/" + item.name }}'
    state: directory
    mode: 0755
    owner: redbot
    group: redbot 
  loop: "{{ redbot }}"

- name: Initialize instance
  shell:
    cmd: redbot "{{ item['name'] }}" --no-prompt --no-cogs --edit --token "{{ item['settings']['token']}}" --prefix "{{ item['settings']['prefix'] }}"
    creates: '{{ data_path + "/" + item.name + "/core"}}'
  become: True
  become_user: redbot

  loop: "{{ redbot }}"
